cfg = {'model_cfg':{"shared_input_dim":13,
                "flatten_input_dim":5,
                "res_input_dim":2,
                "thk_input_dim":2,
                "flatten_y_dims":5,
                "res_y_dims":9,
                "thk_y_dims":31,},
       'batch_size':64,
       'epochs':20,
       'lr':0.001,}