cfg = {'model_cfg':{"shared_input_dim":13,
                "flatten_input_dim":5,
                "res_input_dim":2,
                "thk_input_dim":2,
                "flatten_y_dims":5,
                "res_y_dims":9,
                "thk_y_dims":31,
                "embedding_dim":128,},
       'batch_size':2048,
       'epochs':200,
       'lr':0.001,
       'use_weights':True,
       'use_cuda':True,
       'cuda_device_num':1,
       }